### ISSUE TITLE
Add DNS nameservers option

### ISSUE THREAD

**Issue by cmoulliard** [jimmidyson/packer-boxes#1]
Is it possible to add these DNS nameservers `--dns=8.8.4.4 --dns=8.8.8.8` to the docker options as we get sometimes such error during docker build process

```
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.5-M1:build (default) on project gerrit: Get https://index.docker.io/v1/repositories/fabric8/java/images: dial tcp: lookup index.docker.io: no such host  -> [Help 1]"]
```

**Comment by rhuss** [comment]
And please add also `--log-level="warn"` in `/etc/sysconfig/docker` to avoid spamming the syslog.

**Comment by jimmidyson** [comment]
This isn't a problem any more I don't think.
